# language.py

LANG_DICT = {
    'zh': {
        'lang_name': "中文",
        'title': "全能批量重命名工具 v1.0",
        'lbl_lang': "语言:",
        'lbl_theme': "主题:",
        'theme_light': "浅色",
        'theme_dark': "深色",
        'lbl_dir': "目标文件夹:",
        'btn_browse': "浏览...",
        'tab_num': "🔢 序号重命名",
        'tab_replace': "🔍 查找与替换",
        'lbl_old_range': "当前编号范围:",
        'lbl_new_range': "目标编号范围:",
        'lbl_prefix': "添加文本 (可选):",
        'chk_only_num': "仅保留序号 (抹去原名其他文字)",
        'prefix_placeholder': "留空则保留原名",
        'lbl_find': "查找文本:",
        'lbl_replace': "替换为:",
        'chk_regex': "启用正则表达式匹配",
        'btn_preview': " 预览修改",
        'btn_rename': " ⚡ 执行重命名",
        'btn_undo': " ↩️ 撤销上次修改",
        'lbl_preview': "修改预览清单",
        'tree_old': "修改前文件名",
        'tree_new': "修改后（预览）",
        'msg_title_notice': "提示",
        'msg_title_err': "错误",
        'msg_title_warn': "警告",
        'msg_title_confirm': "确认",
        'msg_title_success': "成功",
        'msg_select_dir': "请先选择目标文件夹",
        'msg_read_dir_failed': "读取文件夹失败：{}",
        'msg_invalid_num': "请输入有效的数字范围",
        'msg_range_err': "当前范围无效：起始编号不能大于结束编号",
        'msg_no_files': "未找到符合条件的文件",
        'msg_preview_first': "请先点击\"预览修改\"查看效果",
        'msg_confirm_rename': "即将修改 {} 个文件，确认继续？",
        'msg_rename_success': "✅ 重命名成功！",
        'msg_file_busy': "文件被占用，请关闭正在使用这些文件的程序后重试",
        'msg_rename_failed': "重命名失败：{}\n部分文件可能已被修改，建议手动检查文件夹。",
        'msg_no_undo_history': "没有可恢复的历史记录",
        'msg_confirm_undo': "确定要将这 {} 个文件恢复到改名前的状态吗？",
        'msg_undo_success': "✅ 已成功撤销上次重命名！",
        'msg_undo_failed': "撤销失败：{}\n部分文件可能已成功回退，请前往文件夹检查。",
        'range_invalid_text': "当前范围无效",
        'msg_regex_err': "正则表达式语法错误，请检查输入",
        'lbl_num_group': "数字组序号:",
        'num_group_default': "1",
        'num_group_tip': "选择文件名中第几组数字作为编号",
        'chk_reverse': "🔄 倒序编号",
        'lbl_ext_filter': "扩展名筛选 (逗号分隔):",
        'ext_placeholder': "留空表示全部文件",
        'lbl_pad_width': "编号位数   :",
        'pad_tip': "补零，如 1→001",
        'chk_use_original_order': "按当前文件名顺序（忽略原有编号）",
        'chk_sort_by_time': "📅 按修改时间排序",
        'sort_by_time_tip': "从旧到新排列",
        'msg_invalid_pad': "请输入有效的位数 (1-10)",
        'tab_order': "📋 按顺序重命名",
        'tab_time': "📅 按时间重命名",
        'lbl_range_setting': "编号范围设置",
        'lbl_name_format': "文件名格式",
        'lbl_sort_setting': "排序设置",
        'lbl_num_setting': "编号设置",
        'lbl_file_filter': "文件筛选",
        'lbl_find_setting': "查找设置",
        'lbl_replace_setting': "替换设置",
        'lbl_start_num': "起始编号:",
        'order_tip': "按文件名顺序（A→Z）",
        'time_tip': "按修改时间（旧→新）",
        'lbl_position': "添加方式:",
        'pos_prefix': "前缀",
        'pos_suffix': "后缀",
        'pos_before': "在编号前",
        'pos_after': "在编号后",
        'msg_temp_recovered': "检测到 {} 个上次异常退出遗留的临时文件，已自动恢复原文件名。",
        'msg_find_empty': "请输入要查找的文本",
    },
    'en': {
        'lang_name': "English",
        'title': "Batch Renamer Tool v1.0",
        'lbl_lang': "Language:",
        'lbl_theme': "Theme:",
        'theme_light': "Light",
        'theme_dark': "Dark",
        'lbl_dir': "Target Folder:",
        'btn_browse': "Browse...",
        'tab_num': "🔢 Index Rename",
        'tab_replace': "🔍 Find & Replace",
        'lbl_old_range': "Current Range:",
        'lbl_new_range': "Target Range:",
        'lbl_prefix': "Text (Optional):",
        'chk_only_num': "Keep index only",
        'prefix_placeholder': "Empty to keep original name",
        'lbl_find': "Find Text:",
        'lbl_replace': "Replace With:",
        'chk_regex': "Enable Regular Expression",
        'btn_preview': " Preview Changes",
        'btn_rename': "⚡Execute Rename",
        'btn_undo': " ↩️ Undo Rename",
        'lbl_preview': "Preview Changes List",
        'tree_old': "Original Filename",
        'tree_new': "New Filename (Preview)",
        'msg_title_notice': "Notice",
        'msg_title_err': "Error",
        'msg_title_warn': "Warning",
        'msg_title_confirm': "Confirm",
        'msg_title_success': "Success",
        'msg_select_dir': "Please select a target folder first",
        'msg_read_dir_failed': "Failed to read folder: {}",
        'msg_invalid_num': "Please enter a valid numeric range",
        'msg_range_err': "Invalid range: Start index cannot be greater than End index",
        'msg_no_files': "No matching files found",
        'msg_preview_first': "Please click \"Preview Changes\" first to see the changes",
        'msg_confirm_rename': "About to rename {} files. Are you sure you want to proceed?",
        'msg_rename_success': "✅ Renamed successfully!",
        'msg_file_busy': "File is in use. Please close programs using these files and try again.",
        'msg_rename_failed': "Rename failed: {}\nSome files may have been changed, please check manually.",
        'msg_no_undo_history': "No history available to restore",
        'msg_confirm_undo': "Are you sure you want to restore these {} files to their original names?",
        'msg_undo_success': "✅ Undo successful!",
        'msg_undo_failed': "Undo failed: {}\nSome files may have been restored, please check.",
        'range_invalid_text': "Invalid range",
        'msg_regex_err': "Invalid regex syntax, please check your input",
        'lbl_num_group': "Number Group:",
        'num_group_default': "1",
        'num_group_tip': "Which group of numbers to use",
        'chk_reverse': "🔄 Reverse Order",
        'lbl_ext_filter': "Extension Filter (comma separated):",
        'ext_placeholder': "Empty for all files",
        'lbl_pad_width': "Padding Width:",
        'pad_tip': "Zero padding, e.g. 1→001",
        'chk_use_original_order': "Use current filename order",
        'chk_sort_by_time': "📅 Sort by modification time",
        'sort_by_time_tip': "From oldest to newest",
        'msg_invalid_pad': "Please enter a valid width (1-10)",
        'tab_order': "📋 Order Rename",
        'tab_time': "📅 Time Rename",
        'lbl_range_setting': "Range Setting",
        'lbl_name_format': "Filename Format",
        'lbl_sort_setting': "Sort Setting",
        'lbl_num_setting': "Number Setting",
        'lbl_file_filter': "File Filter",
        'lbl_find_setting': "Find Setting",
        'lbl_replace_setting': "Replace Setting",
        'lbl_start_num': "Start Number:",
        'order_tip': "By filename order (A→Z)",
        'time_tip': "By modification time (old→new)",
        'lbl_position': "Add as:",
        'pos_prefix': "Prefix",
        'pos_suffix': "Suffix",
        'pos_before': "Before number",
        'pos_after': "After number",
        'msg_temp_recovered': "Found {} leftover temp file(s) from a previous crash; restored their original names.",
        'msg_find_empty': "Please enter the text to find",
    },
    'zh_tw': {
        'lang_name': "繁體中文",
        'title': "全能批量重新命名工具 v1.0",
        'lbl_lang': "語言:",
        'lbl_theme': "主題:",
        'theme_light': "淺色",
        'theme_dark': "深色",
        'lbl_dir': "目標資料夾:",
        'btn_browse': "瀏覽...",
        'tab_num': "🔢 序號重新命名",
        'tab_replace': "🔍 尋找與取代",
        'lbl_old_range': "目前編號範圍:",
        'lbl_new_range': "目標編號範圍:",
        'lbl_prefix': "新增文字 (選填):",
        'chk_only_num': "僅保留序號 (移除原名其他文字)",
        'prefix_placeholder': "留空則保留原名",
        'lbl_find': "尋找文字:",
        'lbl_replace': "取代為:",
        'chk_regex': "啟用正規表達式比對",
        'btn_preview': " 預覽修改",
        'btn_rename': " ⚡ 執行重新命名",
        'btn_undo': " ↩️ 復原上次修改",
        'lbl_preview': "修改預覽清單",
        'tree_old': "修改前檔案名稱",
        'tree_new': "修改後（預覽）",
        'msg_title_notice': "提示",
        'msg_title_err': "錯誤",
        'msg_title_warn': "警告",
        'msg_title_confirm': "確認",
        'msg_title_success': "成功",
        'msg_select_dir': "請先選擇目標資料夾",
        'msg_read_dir_failed': "讀取資料夾失敗：{}",
        'msg_invalid_num': "請輸入有效的數字範圍",
        'msg_range_err': "目前範圍無效：起始編號不能大於結束編號",
        'msg_no_files': "未找到符合條件的檔案",
        'msg_preview_first': "請先點擊「預覽修改」查看效果",
        'msg_confirm_rename': "即將修改 {} 個檔案，確認繼續？",
        'msg_rename_success': "✅ 重新命名成功！",
        'msg_file_busy': "檔案被占用，請關閉正在使用這些檔案的程式後重試",
        'msg_rename_failed': "重新命名失敗：{}\n部分檔案可能已被修改，建議手動檢查資料夾。",
        'msg_no_undo_history': "沒有可復原的歷史記錄",
        'msg_confirm_undo': "確定要將這 {} 個檔案恢復到改名前的狀態嗎？",
        'msg_undo_success': "✅ 已成功復原上次重新命名！",
        'msg_undo_failed': "復原失敗：{}\n部分檔案可能已成功回退，請前往資料夾檢查。",
        'range_invalid_text': "目前範圍無效",
        'msg_regex_err': "正規表達式語法錯誤，請檢查輸入",
        'lbl_num_group': "數字組序號:",
        'num_group_default': "1",
        'num_group_tip': "選擇檔案名稱中第幾組數字作為編號",
        'chk_reverse': "🔄 倒序編號",
        'lbl_ext_filter': "副檔名篩選 (逗號分隔):",
        'ext_placeholder': "留空表示全部檔案",
        'lbl_pad_width': "編號位數   :",
        'pad_tip': "補零，如 1→001",
        'chk_use_original_order': "按目前檔案名稱順序（忽略原有編號）",
        'chk_sort_by_time': "📅 按修改時間排序",
        'sort_by_time_tip': "從舊到新排列",
        'msg_invalid_pad': "請輸入有效的位數 (1-10)",
        'tab_order': "📋 按順序重新命名",
        'tab_time': "📅 按時間重新命名",
        'lbl_range_setting': "編號範圍設定",
        'lbl_name_format': "檔案名稱格式",
        'lbl_sort_setting': "排序設定",
        'lbl_num_setting': "編號設定",
        'lbl_file_filter': "檔案篩選",
        'lbl_find_setting': "尋找設定",
        'lbl_replace_setting': "取代設定",
        'lbl_start_num': "起始編號:",
        'order_tip': "按檔案名稱順序（A→Z）",
        'time_tip': "按修改時間（舊→新）",
        'lbl_position': "新增方式:",
        'pos_prefix': "前綴",
        'pos_suffix': "後綴",
        'pos_before': "在編號前",
        'pos_after': "在編號後",
        'msg_temp_recovered': "檢測到 {} 個上次異常退出遺留的暫存檔案，已自動恢復原檔案名稱。",
        'msg_find_empty': "請輸入要尋找的文字",
    },
    'ja': {
        'lang_name': "日本語",
        'title': "万能一括リネームツール v1.0",
        'lbl_lang': "言語:",
        'lbl_theme': "テーマ:",
        'theme_light': "ライト",
        'theme_dark': "ダーク",
        'lbl_dir': "対象フォルダ:",
        'btn_browse': "参照...",
        'tab_num': "🔢 連番リネーム",
        'tab_replace': "🔍 検索と置換",
        'lbl_old_range': "現在の番号範囲:",
        'lbl_new_range': "対象の番号範囲:",
        'lbl_prefix': "テキストを追加 (任意):",
        'chk_only_num': "連番のみ保持 (元の名前を削除)",
        'prefix_placeholder': "空欄で元の名前を保持",
        'lbl_find': "検索テキスト:",
        'lbl_replace': "置換テキスト:",
        'chk_regex': "正規表現を使用",
        'btn_preview': " プレビュー",
        'btn_rename': " ⚡ リネーム実行",
        'btn_undo': " ↩️ 元に戻す",
        'lbl_preview': "変更プレビュー一覧",
        'tree_old': "変更前のファイル名",
        'tree_new': "変更後（プレビュー）",
        'msg_title_notice': "通知",
        'msg_title_err': "エラー",
        'msg_title_warn': "警告",
        'msg_title_confirm': "確認",
        'msg_title_success': "成功",
        'msg_select_dir': "対象フォルダを選択してください",
        'msg_read_dir_failed': "フォルダの読み込みに失敗しました：{}",
        'msg_invalid_num': "有効な数値範囲を入力してください",
        'msg_range_err': "範囲が無効です：開始番号は終了番号より大きくできません",
        'msg_no_files': "条件に一致するファイルが見つかりません",
        'msg_preview_first': "先に「プレビュー」をクリックして変更を確認してください",
        'msg_confirm_rename': "{} 個のファイルを変更します。続行してもよろしいですか？",
        'msg_rename_success': "✅ リネームに成功しました！",
        'msg_file_busy': "ファイルが使用中です。該当ファイルを使用中のプログラムを閉じてから再試行してください",
        'msg_rename_failed': "リネームに失敗しました：{}\n一部のファイルは変更されている可能性があります。フォルダを手動で確認してください。",
        'msg_no_undo_history': "復元可能な履歴がありません",
        'msg_confirm_undo': "この {} 個のファイルをリネーム前の名前に戻しますか？",
        'msg_undo_success': "✅ 元に戻すことに成功しました！",
        'msg_undo_failed': "元に戻せませんでした：{}\n一部のファイルは復元されている可能性があります。フォルダを確認してください。",
        'range_invalid_text': "範囲が無効です",
        'msg_regex_err': "正規表現の構文エラーです。入力を確認してください",
        'lbl_num_group': "数字グループ番号:",
        'num_group_default': "1",
        'num_group_tip': "ファイル名の何番目の数字グループを連番として使用するか選択",
        'chk_reverse': "🔄 逆順連番",
        'lbl_ext_filter': "拡張子フィルター (カンマ区切り):",
        'ext_placeholder': "空欄ですべてのファイル",
        'lbl_pad_width': "桁数指定   :",
        'pad_tip': "ゼロ埋め、例：1→001",
        'chk_use_original_order': "現在のファイル名順を使用（元の連番を無視）",
        'chk_sort_by_time': "📅 更新日時でソート",
        'sort_by_time_tip': "古い順に並べ替え",
        'msg_invalid_pad': "有効な桁数 (1-10) を入力してください",
        'tab_order': "📋 順序リネーム",
        'tab_time': "📅 時間リネーム",
        'lbl_range_setting': "範囲設定",
        'lbl_name_format': "ファイル名形式",
        'lbl_sort_setting': "ソート設定",
        'lbl_num_setting': "番号設定",
        'lbl_file_filter': "ファイルフィルター",
        'lbl_find_setting': "検索設定",
        'lbl_replace_setting': "置換設定",
        'lbl_start_num': "開始番号:",
        'order_tip': "ファイル名順（A→Z）",
        'time_tip': "更新日時順（古→新）",
        'lbl_position': "追加位置:",
        'pos_prefix': "接頭辞",
        'pos_suffix': "接尾辞",
        'pos_before': "番号の前",
        'pos_after': "番号の後",
        'msg_temp_recovered': "前回の異常終了時に残された {} 個の一時ファイルを検出し、元のファイル名に復元しました。",
        'msg_find_empty': "検索テキストを入力してください",
    },
    'ko': {
        'lang_name': "한국어",
        'title': "올인원 일괄 이름 바꾸기 도구 v1.0",
        'lbl_lang': "언어:",
        'lbl_theme': "테마:",
        'theme_light': "라이트",
        'theme_dark': "다크",
        'lbl_dir': "대상 폴더:",
        'btn_browse': "찾아보기...",
        'tab_num': "🔢 번호순 이름 바꾸기",
        'tab_replace': "🔍 찾기 및 바꾸기",
        'lbl_old_range': "현재 번호 범위:",
        'lbl_new_range': "대상 번호 범위:",
        'lbl_prefix': "텍스트 추가 (선택):",
        'chk_only_num': "번호만 유지 (원래 이름의 다른 텍스트 제거)",
        'prefix_placeholder': "비워두면 원래 이름 유지",
        'lbl_find': "찾을 텍스트:",
        'lbl_replace': "바꿀 텍스트:",
        'chk_regex': "정규 표현식 사용",
        'btn_preview': " 미리보기",
        'btn_rename': " ⚡ 이름 바꾸기 실행",
        'btn_undo': " ↩️ 실행 취소",
        'lbl_preview': "변경 미리보기 목록",
        'tree_old': "변경 전 파일명",
        'tree_new': "변경 후 (미리보기)",
        'msg_title_notice': "알림",
        'msg_title_err': "오류",
        'msg_title_warn': "경고",
        'msg_title_confirm': "확인",
        'msg_title_success': "성공",
        'msg_select_dir': "대상 폴더를 먼저 선택하세요",
        'msg_read_dir_failed': "폴더 읽기 실패: {}",
        'msg_invalid_num': "유효한 숫자 범위를 입력하세요",
        'msg_range_err': "범위가 유효하지 않음: 시작 번호는 끝 번호보다 클 수 없습니다",
        'msg_no_files': "조건에 맞는 파일을 찾을 수 없습니다",
        'msg_preview_first': "먼저 '미리보기'를 클릭하여 변경 내용을 확인하세요",
        'msg_confirm_rename': "{} 개의 파일을 변경합니다. 계속하시겠습니까?",
        'msg_rename_success': "✅ 이름 바꾸기 성공!",
        'msg_file_busy': "파일이 사용 중입니다. 해당 파일을 사용 중인 프로그램을 닫고 다시 시도하세요",
        'msg_rename_failed': "이름 바꾸기 실패: {}\n일부 파일이 이미 변경되었을 수 있습니다. 폴더를 수동으로 확인하세요.",
        'msg_no_undo_history': "복원할 기록이 없습니다",
        'msg_confirm_undo': "이 {} 개의 파일을 원래 이름으로 복원하시겠습니까?",
        'msg_undo_success': "✅ 실행 취소 성공!",
        'msg_undo_failed': "실행 취소 실패: {}\n일부 파일이 복원되었을 수 있습니다. 폴더를 확인하세요.",
        'range_invalid_text': "범위가 유효하지 않음",
        'msg_regex_err': "정규 표현식 구문 오류입니다. 입력을 확인하세요",
        'lbl_num_group': "숫자 그룹 번호:",
        'num_group_default': "1",
        'num_group_tip': "파일명에서 몇 번째 숫자 그룹을 번호로 사용할지 선택",
        'chk_reverse': "🔄 역순 번호",
        'lbl_ext_filter': "확장자 필터 (쉼표로 구분):",
        'ext_placeholder': "비워두면 모든 파일",
        'lbl_pad_width': "자릿수   :",
        'pad_tip': "빈 자리 채우기, 예: 1→001",
        'chk_use_original_order': "현재 파일명 순서 사용 (기존 번호 무시)",
        'chk_sort_by_time': "📅 수정 시간순 정렬",
        'sort_by_time_tip': "오래된 순서대로 정렬",
        'msg_invalid_pad': "유효한 자릿수 (1-10)를 입력하세요",
        'tab_order': "📋 순서대로 이름 바꾸기",
        'tab_time': "📅 시간순 이름 바꾸기",
        'lbl_range_setting': "범위 설정",
        'lbl_name_format': "파일명 형식",
        'lbl_sort_setting': "정렬 설정",
        'lbl_num_setting': "번호 설정",
        'lbl_file_filter': "파일 필터",
        'lbl_find_setting': "찾기 설정",
        'lbl_replace_setting': "바꾸기 설정",
        'lbl_start_num': "시작 번호:",
        'order_tip': "파일명 순서 (A→Z)",
        'time_tip': "수정 시간순 (오래된→새로운)",
        'lbl_position': "추가 위치:",
        'pos_prefix': "접두사",
        'pos_suffix': "접미사",
        'pos_before': "번호 앞에",
        'pos_after': "번호 뒤에",
        'msg_temp_recovered': "이전 비정상 종료 시 남은 {} 개의 임시 파일을 발견하여 원래 파일명으로 복원했습니다.",
        'msg_find_empty': "찾을 텍스트를 입력하세요",
    },
    'fr': {
        'lang_name': "Français",
        'title': "Outil de Renommage par Lots Tout-en-un v1.0",
        'lbl_lang': "Langue:",
        'lbl_theme': "Thème:",
        'theme_light': "Clair",
        'theme_dark': "Sombre",
        'lbl_dir': "Dossier cible:",
        'btn_browse': "Parcourir...",
        'tab_num': "🔢 Renommage par numéro",
        'tab_replace': "🔍 Rechercher et remplacer",
        'lbl_old_range': "Plage actuelle:",
        'lbl_new_range': "Plage cible:",
        'lbl_prefix': "Ajouter du texte (optionnel):",
        'chk_only_num': "Garder uniquement le numéro (supprimer le texte original)",
        'prefix_placeholder': "Laisser vide pour garder le nom original",
        'lbl_find': "Texte à rechercher:",
        'lbl_replace': "Remplacer par:",
        'chk_regex': "Utiliser les expressions régulières",
        'btn_preview': " Aperçu",
        'btn_rename': " ⚡ Renommer",
        'btn_undo': " ↩️ Annuler",
        'lbl_preview': "Liste des modifications",
        'tree_old': "Nom original",
        'tree_new': "Nouveau nom (aperçu)",
        'msg_title_notice': "Avis",
        'msg_title_err': "Erreur",
        'msg_title_warn': "Avertissement",
        'msg_title_confirm': "Confirmation",
        'msg_title_success': "Succès",
        'msg_select_dir': "Veuillez d'abord sélectionner un dossier cible",
        'msg_read_dir_failed': "Échec de lecture du dossier : {}",
        'msg_invalid_num': "Veuillez entrer une plage numérique valide",
        'msg_range_err': "Plage invalide : le numéro de début ne peut pas être supérieur au numéro de fin",
        'msg_no_files': "Aucun fichier correspondant trouvé",
        'msg_preview_first': "Veuillez d'abord cliquer sur « Aperçu des modifications » pour voir les changements",
        'msg_confirm_rename': "Vous allez renommer {} fichier(s). Confirmez-vous ?",
        'msg_rename_success': "✅ Renommage réussi !",
        'msg_file_busy': "Fichier utilisé. Veuillez fermer les programmes utilisant ces fichiers et réessayer.",
        'msg_rename_failed': "Échec du renommage : {}\nCertains fichiers ont peut-être été modifiés. Vérifiez manuellement le dossier.",
        'msg_no_undo_history': "Aucun historique à restaurer",
        'msg_confirm_undo': "Voulez-vous vraiment restaurer ces {} fichiers à leur nom d'origine ?",
        'msg_undo_success': "✅ Annulation réussie !",
        'msg_undo_failed': "Échec de l'annulation : {}\nCertains fichiers ont peut-être été restaurés. Veuillez vérifier le dossier.",
        'range_invalid_text': "Plage invalide",
        'msg_regex_err': "Erreur de syntaxe dans l'expression régulière, vérifiez votre saisie",
        'lbl_num_group': "Groupe de numéros:",
        'num_group_default': "1",
        'num_group_tip': "Choisir quel groupe de nombres dans le nom de fichier utiliser comme numéro",
        'chk_reverse': "🔄 Ordre inverse",
        'lbl_ext_filter': "Filtre d'extension (séparé par des virgules):",
        'ext_placeholder': "Vide pour tous les fichiers",
        'lbl_pad_width': "Largeur de remplissage:",
        'pad_tip': "Remplir avec des zéros, ex: 1→001",
        'chk_use_original_order': "Utiliser l'ordre actuel des noms de fichiers (ignorer les numéros existants)",
        'chk_sort_by_time': "📅 Trier par date de modification",
        'sort_by_time_tip': "Du plus ancien au plus récent",
        'msg_invalid_pad': "Veuillez entrer une largeur valide (1-10)",
        'tab_order': "📋 Renommage par ordre",
        'tab_time': "📅 Renommage par date",
        'lbl_range_setting': "Paramètres de plage",
        'lbl_name_format': "Format du nom de fichier",
        'lbl_sort_setting': "Paramètres de tri",
        'lbl_num_setting': "Paramètres de numérotation",
        'lbl_file_filter': "Filtre de fichiers",
        'lbl_find_setting': "Paramètres de recherche",
        'lbl_replace_setting': "Paramètres de remplacement",
        'lbl_start_num': "Numéro de départ:",
        'order_tip': "Par ordre de nom de fichier (A→Z)",
        'time_tip': "Par date de modification (ancien→nouveau)",
        'lbl_position': "Ajouter en tant que:",
        'pos_prefix': "Préfixe",
        'pos_suffix': "Suffixe",
        'pos_before': "Avant le numéro",
        'pos_after': "Après le numéro",
        'msg_temp_recovered': "{} fichier(s) temporaire(s) trouvé(s) suite à une fermeture anormale ; leurs noms originaux ont été restaurés.",
        'msg_find_empty': "Veuillez entrer le texte à rechercher",
    },
    'de': {
        'lang_name': "Deutsch",
        'title': "All-in-One Stapelumbenennungstool v1.0",
        'lbl_lang': "Sprache:",
        'lbl_theme': "Thema:",
        'theme_light': "Hell",
        'theme_dark': "Dunkel",
        'lbl_dir': "Zielordner:",
        'btn_browse': "Durchsuchen...",
        'tab_num': "🔢 Nummerische Umbenennung",
        'tab_replace': "🔍 Suchen und Ersetzen",
        'lbl_old_range': "Aktueller Nummernbereich:",
        'lbl_new_range': "Zielnummernbereich:",
        'lbl_prefix': "Text hinzufügen (optional):",
        'chk_only_num': "Nur Nummer behalten (ursprünglichen Text entfernen)",
        'prefix_placeholder': "Leer lassen, um ursprünglichen Namen zu behalten",
        'lbl_find': "Suchtext:",
        'lbl_replace': "Ersetzen mit:",
        'chk_regex': "Reguläre Ausdrücke verwenden",
        'btn_preview': " Vorschau",
        'btn_rename': " ⚡ Umbenennen",
        'btn_undo': " ↩️ Rückgängig",
        'lbl_preview': "Vorschau der Änderungen",
        'tree_old': "Ursprünglicher Dateiname",
        'tree_new': "Neuer Dateiname (Vorschau)",
        'msg_title_notice': "Hinweis",
        'msg_title_err': "Fehler",
        'msg_title_warn': "Warnung",
        'msg_title_confirm': "Bestätigung",
        'msg_title_success': "Erfolg",
        'msg_select_dir': "Bitte wählen Sie zuerst einen Zielordner aus",
        'msg_read_dir_failed': "Ordner konnte nicht gelesen werden: {}",
        'msg_invalid_num': "Bitte geben Sie einen gültigen Zahlenbereich ein",
        'msg_range_err': "Ungültiger Bereich: Startnummer darf nicht größer als Endnummer sein",
        'msg_no_files': "Keine passenden Dateien gefunden",
        'msg_preview_first': "Bitte klicken Sie zuerst auf «Vorschau», um die Änderungen zu sehen",
        'msg_confirm_rename': "Sie sind dabei, {} Datei(en) umzubenennen. Möchten Sie fortfahren?",
        'msg_rename_success': "✅ Umbenennung erfolgreich!",
        'msg_file_busy': "Datei wird verwendet. Bitte schließen Sie Programme, die diese Dateien verwenden, und versuchen Sie es erneut.",
        'msg_rename_failed': "Umbenennung fehlgeschlagen: {}\nEinige Dateien wurden möglicherweise bereits geändert. Bitte prüfen Sie den Ordner manuell.",
        'msg_no_undo_history': "Kein Verlauf zum Wiederherstellen verfügbar",
        'msg_confirm_undo': "Möchten Sie diese {} Datei(en) wirklich zu ihren ursprünglichen Namen zurücksetzen?",
        'msg_undo_success': "✅ Rückgängig erfolgreich!",
        'msg_undo_failed': "Rückgängig fehlgeschlagen: {}\nEinige Dateien wurden möglicherweise bereits zurückgesetzt. Bitte prüfen Sie den Ordner.",
        'range_invalid_text': "Ungültiger Bereich",
        'msg_regex_err': "Syntaxfehler im regulären Ausdruck, bitte überprüfen Sie Ihre Eingabe",
        'lbl_num_group': "Zahlengruppe:",
        'num_group_default': "1",
        'num_group_tip': "Wählen Sie, welche Zahlengruppe im Dateinamen als Nummer verwendet werden soll",
        'chk_reverse': "🔄 Umgekehrte Reihenfolge",
        'lbl_ext_filter': "Erweiterungsfilter (kommagetrennt):",
        'ext_placeholder': "Leer für alle Dateien",
        'lbl_pad_width': "Stellenzahl:",
        'pad_tip': "Mit Nullen auffüllen, z.B. 1→001",
        'chk_use_original_order': "Aktuelle Dateinamenreihenfolge verwenden (vorhandene Nummern ignorieren)",
        'chk_sort_by_time': "📅 Nach Änderungsdatum sortieren",
        'sort_by_time_tip': "Von alt nach neu",
        'msg_invalid_pad': "Bitte geben Sie eine gültige Stellenzahl (1-10) ein",
        'tab_order': "📋 Nach Reihenfolge umbenennen",
        'tab_time': "📅 Nach Datum umbenennen",
        'lbl_range_setting': "Bereichseinstellungen",
        'lbl_name_format': "Dateinamenformat",
        'lbl_sort_setting': "Sortiereinstellungen",
        'lbl_num_setting': "Nummerierungseinstellungen",
        'lbl_file_filter': "Dateifilter",
        'lbl_find_setting': "Sucheinstellungen",
        'lbl_replace_setting': "Ersetzungseinstellungen",
        'lbl_start_num': "Startnummer:",
        'order_tip': "Nach Dateinamenreihenfolge (A→Z)",
        'time_tip': "Nach Änderungsdatum (alt→neu)",
        'lbl_position': "Hinzufügen als:",
        'pos_prefix': "Präfix",
        'pos_suffix': "Suffix",
        'pos_before': "Vor der Nummer",
        'pos_after': "Nach der Nummer",
        'msg_temp_recovered': "{} temporäre Datei(en) von einem vorherigen Absturz gefunden und ursprüngliche Namen wiederhergestellt.",
        'msg_find_empty': "Bitte geben Sie den zu suchenden Text ein",
    },
    'es': {
        'lang_name': "Español",
        'title': "Herramienta de Renombrado Masivo Todo-en-Uno v1.0",
        'lbl_lang': "Idioma:",
        'lbl_theme': "Tema:",
        'theme_light': "Claro",
        'theme_dark': "Oscuro",
        'lbl_dir': "Carpeta de destino:",
        'btn_browse': "Examinar...",
        'tab_num': "🔢 Renombrado por número",
        'tab_replace': "🔍 Buscar y reemplazar",
        'lbl_old_range': "Rango actual:",
        'lbl_new_range': "Rango de destino:",
        'lbl_prefix': "Añadir texto (opcional):",
        'chk_only_num': "Conservar solo el número (eliminar otro texto del nombre)",
        'prefix_placeholder': "Dejar vacío para conservar el nombre original",
        'lbl_find': "Texto a buscar:",
        'lbl_replace': "Reemplazar con:",
        'chk_regex': "Usar expresiones regulares",
        'btn_preview': " Vista previa",
        'btn_rename': " ⚡ Renombrar",
        'btn_undo': " ↩️ Deshacer",
        'lbl_preview': "Lista de cambios",
        'tree_old': "Nombre original",
        'tree_new': "Nuevo nombre (vista previa)",
        'msg_title_notice': "Aviso",
        'msg_title_err': "Error",
        'msg_title_warn': "Advertencia",
        'msg_title_confirm': "Confirmar",
        'msg_title_success': "Éxito",
        'msg_select_dir': "Seleccione primero una carpeta de destino",
        'msg_read_dir_failed': "Error al leer la carpeta: {}",
        'msg_invalid_num': "Introduzca un rango numérico válido",
        'msg_range_err': "Rango inválido: el número inicial no puede ser mayor que el número final",
        'msg_no_files': "No se encontraron archivos que cumplan los criterios",
        'msg_preview_first': "Primero haga clic en «Vista previa» para ver los cambios",
        'msg_confirm_rename': "Va a renombrar {} archivo(s). ¿Confirma que desea continuar?",
        'msg_rename_success': "✅ ¡Renombrado exitoso!",
        'msg_file_busy': "El archivo está en uso. Cierre los programas que utilicen estos archivos y vuelva a intentarlo.",
        'msg_rename_failed': "Error al renombrar: {}\nEs posible que algunos archivos ya hayan sido modificados. Verifique la carpeta manualmente.",
        'msg_no_undo_history': "No hay historial disponible para restaurar",
        'msg_confirm_undo': "¿Está seguro de que desea restaurar estos {} archivos a sus nombres originales?",
        'msg_undo_success': "✅ ¡Deshacer exitoso!",
        'msg_undo_failed': "Error al deshacer: {}\nEs posible que algunos archivos ya hayan sido restaurados. Verifique la carpeta.",
        'range_invalid_text': "Rango inválido",
        'msg_regex_err': "Error de sintaxis en la expresión regular, verifique su entrada",
        'lbl_num_group': "Grupo de números:",
        'num_group_default': "1",
        'num_group_tip': "Seleccionar qué grupo de números en el nombre del archivo usar como número",
        'chk_reverse': "🔄 Orden inverso",
        'lbl_ext_filter': "Filtro de extensión (separado por comas):",
        'ext_placeholder': "Vacío para todos los archivos",
        'lbl_pad_width': "Ancho de relleno:",
        'pad_tip': "Rellenar con ceros, ej: 1→001",
        'chk_use_original_order': "Usar el orden actual de nombres de archivos (ignorar números existentes)",
        'chk_sort_by_time': "📅 Ordenar por fecha de modificación",
        'sort_by_time_tip': "De más antiguo a más nuevo",
        'msg_invalid_pad': "Introduzca un ancho válido (1-10)",
        'tab_order': "📋 Renombrar por orden",
        'tab_time': "📅 Renombrar por fecha",
        'lbl_range_setting': "Configuración de rango",
        'lbl_name_format': "Formato de nombre de archivo",
        'lbl_sort_setting': "Configuración de orden",
        'lbl_num_setting': "Configuración de numeración",
        'lbl_file_filter': "Filtro de archivos",
        'lbl_find_setting': "Configuración de búsqueda",
        'lbl_replace_setting': "Configuración de reemplazo",
        'lbl_start_num': "Número inicial:",
        'order_tip': "Por orden de nombre de archivo (A→Z)",
        'time_tip': "Por fecha de modificación (antiguo→nuevo)",
        'lbl_position': "Añadir como:",
        'pos_prefix': "Prefijo",
        'pos_suffix': "Sufijo",
        'pos_before': "Antes del número",
        'pos_after': "Después del número",
        'msg_temp_recovered': "Se encontraron {} archivo(s) temporal(es) dejados por un cierre anormal anterior; se restauraron sus nombres originales.",
        'msg_find_empty': "Introduzca el texto a buscar",
    }
}